// CI smoke prep (self-contained in the fork): generate a throwaway roster key +
// bot identity, sign a fresh roster + snapshot, publish to the smoke relay, and
// write the ENVFILE the app build consumes (public data only, no secrets).
// Usage: node prep.mjs <relay-url> <envfile-out> [state-dir]
import { writeFileSync, mkdirSync, readFileSync } from "node:fs"
import { TestEventSigner } from "../../vendor/blink-support-chat-adapters/signer.js"
import { SimplePoolNetwork } from "../../vendor/blink-support-chat-adapters/network.js"
import { rosterTemplate } from "../../vendor/blink-support-chat-adapters/roster.js"

const RELAY = process.argv[2]
const ENV_OUT = process.argv[3]
const STATE = process.argv[4] ?? "/tmp/support-chat-smoke-state"
if (!RELAY || !ENV_OUT) throw new Error("usage: prep.mjs <relay-url> <envfile-out> [state-dir]")
mkdirSync(STATE, { recursive: true })

const loadOrCreate = (file) => {
  try {
    return new TestEventSigner(Uint8Array.from(JSON.parse(readFileSync(`${STATE}/${file}`, "utf8")).secretKey))
  } catch {
    const s = new TestEventSigner()
    writeFileSync(`${STATE}/${file}`, JSON.stringify({ secretKey: [...s.secretKeyBytes] }), { mode: 0o600 })
    return s
  }
}
const rosterKey = loadOrCreate("roster-key.json")
const bot = loadOrCreate("bot.json")

const now = Math.floor(Date.now() / 1000)
const members = [{ pubkey: bot.publicKey, name: "CI Smoke Bot", role: "bot" }]
const snapshot = rosterKey.signEvent(rosterTemplate({ members, createdAt: now, expiresAt: now + 2 * 86400, pubkey: rosterKey.publicKey }))

const net = new SimplePoolNetwork({ signer: rosterKey, relays: [RELAY] })
const res = await net.publish([RELAY], snapshot)
await net.destroy()
if (!Object.values(res)[0].ok) throw new Error(`roster publish failed: ${JSON.stringify(res)}`)

writeFileSync(
  ENV_OUT,
  `# generated by prep.mjs — public data only\nSUPPORT_CHAT_RELAY=${RELAY}\nSUPPORT_ROSTER_PUBKEY=${rosterKey.publicKey}\nSUPPORT_ROSTER_SNAPSHOT=${JSON.stringify(snapshot)}\n`,
)
console.log(`roster ${snapshot.id.slice(0, 8)} published to ${RELAY} (expires in 2d)`)
console.log(`bot identity: ${STATE}/bot.json`)
