#!/usr/bin/env bash
# Blink Alpha build env: react-native-config reads ONE env file, and the alpha app needs
# both the wallet settings (.env.local — BREEZ_API_KEY etc., the nostr-signer
# workstream's file, only READ here) and the support-chat settings
# (.env.support-dogfood). Writes .env.alpha (git-ignored, mode 600). Never prints values.
# Usage: scripts/support-chat-alpha/make-env.sh && ENVFILE=.env.alpha …assembleDebug
set -euo pipefail
cd "$(dirname "$0")/../.."
for f in .env.local .env.support-dogfood; do [ -r "$f" ] || { echo "missing $f" >&2; exit 1; }; done
git check-ignore -q .env.alpha || { echo ".env.alpha is not git-ignored" >&2; exit 1; }
umask 077
{
  echo "# generated by scripts/support-chat-alpha/make-env.sh — do not edit, do not commit"
  cat .env.local
  echo
  cat .env.support-dogfood
} > .env.alpha
chmod 600 .env.alpha
# names only, for the build log
echo "wrote .env.alpha: $(grep -oE '^[A-Z_]+=' .env.alpha | tr -d = | sort -u | tr '\n' ' ')"
