/**
 * Pinned roster key + shipped signed snapshot for the support chat (P1 dev scaffold).
 *
 * Spec 03 §4 req 3: the app is the control for who is Blink Support — it pins ONE
 * roster key and fails closed without a valid roster. The shipped snapshot seeds the
 * very first run (patternn review point): the RosterVerifier re-verifies its
 * signature and applies the same floor/expiry rules as to a relay event, and a live
 * roster (newer `created_at`) replaces it.
 *
 * DEV SCAFFOLD (P1): this key is a THROWAWAY test key (generated by
 * blink-support-chat interop/v2/make-roster-snapshot.mjs, state in the git-ignored
 * interop/.p1-state/) — never the product roster key (Amber custody, AGENTS.md).
 * P7 replaces this module with config-driven key/snapshot (no test identities in
 * the shipped build). The snapshot's long dev expiry (2026-12-31) is a test
 * convenience; production rosters are weekly with fail-closed expiry.
 */
import type { Event } from "nostr-tools/pure"

export const SUPPORT_ROSTER_PUBKEY =
  "165567414598ec00ebf368269a1e491cb0279c0d4f404a69ff1d9df8a5fd705d"

export const ROSTER_SNAPSHOT: Event = {
  kind: 30000,
  created_at: 1790731266,
  tags: [
    ["d", "blink-support-team"],
    ["title", "Blink Support team"],
    [
      "p",
      "b01f7dcf7cc4bfa14228a8711eb72325b131e10f20dc2154f1f8785cc5b84e5b",
      "",
      "P1 Test Bot",
    ],
    [
      "role",
      "b01f7dcf7cc4bfa14228a8711eb72325b131e10f20dc2154f1f8785cc5b84e5b",
      "bot",
    ],
    ["expiration", "1798675200"],
  ],
  content: "",
  pubkey: "165567414598ec00ebf368269a1e491cb0279c0d4f404a69ff1d9df8a5fd705d",
  id: "de838f6bdfd7a2ec27d8562921f9d2245a5e5314b36e69f2b8e5e6eeadd75bb3",
  sig: "6648e5cc567fedfc65ef333a2055807d3b78f24d7e4c97fc105ff09b980edd8ec85f2c0e4081218bae76163e0a91d3a0e93c78b39545cfcb8a95201a0237f1fb",
}
